// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kruskal_cols_cpp
NumericVector kruskal_cols_cpp(NumericMatrix X, IntegerVector grp);
RcppExport SEXP _MSclassifR_kruskal_cols_cpp(SEXP XSEXP, SEXP grpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp(grpSEXP);
    rcpp_result_gen = Rcpp::wrap(kruskal_cols_cpp(X, grp));
    return rcpp_result_gen;
END_RCPP
}
// anova_cols_cpp
NumericVector anova_cols_cpp(NumericMatrix X, IntegerVector grp);
RcppExport SEXP _MSclassifR_anova_cols_cpp(SEXP XSEXP, SEXP grpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type grp(grpSEXP);
    rcpp_result_gen = Rcpp::wrap(anova_cols_cpp(X, grp));
    return rcpp_result_gen;
END_RCPP
}
// cpp_match_anchors
List cpp_match_anchors(NumericVector peaks, NumericVector ref, double tol, bool ppm);
RcppExport SEXP _MSclassifR_cpp_match_anchors(SEXP peaksSEXP, SEXP refSEXP, SEXP tolSEXP, SEXP ppmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type peaks(peaksSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ref(refSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type ppm(ppmSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_match_anchors(peaks, ref, tol, ppm));
    return rcpp_result_gen;
END_RCPP
}
// cpp_warp_mz_piecewise
NumericVector cpp_warp_mz_piecewise(NumericVector mz, NumericVector src_anchor, NumericVector dst_anchor);
RcppExport SEXP _MSclassifR_cpp_warp_mz_piecewise(SEXP mzSEXP, SEXP src_anchorSEXP, SEXP dst_anchorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type src_anchor(src_anchorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dst_anchor(dst_anchorSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_warp_mz_piecewise(mz, src_anchor, dst_anchor));
    return rcpp_result_gen;
END_RCPP
}
// map_spectrum_to_moz_cpp
NumericVector map_spectrum_to_moz_cpp(NumericVector moz, NumericVector peak_mz, NumericVector peak_int, double tol, double noMatch);
RcppExport SEXP _MSclassifR_map_spectrum_to_moz_cpp(SEXP mozSEXP, SEXP peak_mzSEXP, SEXP peak_intSEXP, SEXP tolSEXP, SEXP noMatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type moz(mozSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peak_mz(peak_mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type peak_int(peak_intSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type noMatch(noMatchSEXP);
    rcpp_result_gen = Rcpp::wrap(map_spectrum_to_moz_cpp(moz, peak_mz, peak_int, tol, noMatch));
    return rcpp_result_gen;
END_RCPP
}
// build_X_from_peaks_cpp
NumericMatrix build_X_from_peaks_cpp(NumericVector moz, List mass_list, List int_list, double tol, double noMatch, bool normalize);
RcppExport SEXP _MSclassifR_build_X_from_peaks_cpp(SEXP mozSEXP, SEXP mass_listSEXP, SEXP int_listSEXP, SEXP tolSEXP, SEXP noMatchSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type moz(mozSEXP);
    Rcpp::traits::input_parameter< List >::type mass_list(mass_listSEXP);
    Rcpp::traits::input_parameter< List >::type int_list(int_listSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type noMatch(noMatchSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(build_X_from_peaks_cpp(moz, mass_list, int_list, tol, noMatch, normalize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSclassifR_kruskal_cols_cpp", (DL_FUNC) &_MSclassifR_kruskal_cols_cpp, 2},
    {"_MSclassifR_anova_cols_cpp", (DL_FUNC) &_MSclassifR_anova_cols_cpp, 2},
    {"_MSclassifR_cpp_match_anchors", (DL_FUNC) &_MSclassifR_cpp_match_anchors, 4},
    {"_MSclassifR_cpp_warp_mz_piecewise", (DL_FUNC) &_MSclassifR_cpp_warp_mz_piecewise, 3},
    {"_MSclassifR_map_spectrum_to_moz_cpp", (DL_FUNC) &_MSclassifR_map_spectrum_to_moz_cpp, 5},
    {"_MSclassifR_build_X_from_peaks_cpp", (DL_FUNC) &_MSclassifR_build_X_from_peaks_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSclassifR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
