# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kruskal_cols_cpp <- function(X, grp) {
    .Call(`_MSclassifR_kruskal_cols_cpp`, X, grp)
}

anova_cols_cpp <- function(X, grp) {
    .Call(`_MSclassifR_anova_cols_cpp`, X, grp)
}

cpp_match_anchors <- function(peaks, ref, tol, ppm) {
    .Call(`_MSclassifR_cpp_match_anchors`, peaks, ref, tol, ppm)
}

cpp_warp_mz_piecewise <- function(mz, src_anchor, dst_anchor) {
    .Call(`_MSclassifR_cpp_warp_mz_piecewise`, mz, src_anchor, dst_anchor)
}

map_spectrum_to_moz_cpp <- function(moz, peak_mz, peak_int, tol, noMatch = 0.0) {
    .Call(`_MSclassifR_map_spectrum_to_moz_cpp`, moz, peak_mz, peak_int, tol, noMatch)
}

build_X_from_peaks_cpp <- function(moz, mass_list, int_list, tol, noMatch = 0.0, normalize = TRUE) {
    .Call(`_MSclassifR_build_X_from_peaks_cpp`, moz, mass_list, int_list, tol, noMatch, normalize)
}

